id: IEBAB88B5
legacy_id: P004237
ocr_import_info:
  bdrc_scan_id: W1KG877
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T18:25:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:03:52.924237+00:00'
last_modified: 2022-09-01 02:04:10.364170
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG877
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG877
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྔ་འགྱུར་རྡོ་རྗེ་ཐེག་པའི་བསྟན་པ་རིན་པོ་ཆེའི་ཇི་ལྟར་བྱུང་བའི་ཚུལ།
  author: བདུད་འཇོམས་འཇིགས་བྲལ་ཡེ་ཤེས་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.9645140412598777
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG934:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG934
      total_pages: 590
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG934.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9645140412598777
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
